---
  - name: Create a user
    user: 
      name: "{{ user_name }}"
      shell: /bin/bash
      system: yes
      create_home: no

  - name: Create a folder for app
    file:
      path: "{{ app_dir }}"
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: u=rwX,g=rX,o=rX
      recurse: true

  - name: Install python
    yum:
      name:
        - python3
        - python3-pip
        - python3-virtualenv
      state: present